// Maps every possible speak() text → audio file key.
// Keys correspond to public/audio/{key}.mp3
// Generated by: npm run generate-audio

// ── Helpers used to build map entries ─────────────────────────────────────────

const LETTER_HINT = {
  A: 'auto',    O: 'oko',
  M: 'mama',    K: 'kuća',
  S: 'sunce',   L: 'lopta',
  T: 'tata',    N: 'nos',
  R: 'riba',    E: 'evo',
  I: 'igra',    U: 'uho',
  V: 'voda',    P: 'pas',
  G: 'gora',    H: 'hlače',
  C: 'cesta',   Z: 'zima',
  J: 'jabuka',  D: 'drvo',
  F: 'foto',
  b: 'brod',    d: 'drvo',
  p: 'pas',     n: 'nos',
  m: 'more',    u: 'uho',
};

// ZvucnaZagonetka targets (uppercase + confusable lowercase)
const ZZ_TARGETS_UPPER = ['A','K','T','M','S','O','R','E','I','V','P','G','H','C','Z','J','D','L'];
const ZZ_TARGETS_LOWER = ['b','d','p','n','m','u'];

// SumskaSlagalica — all display words
const SS_WORDS = [
  'Vuk','Som','Rak','Jež','Kos','Ris','Zec','Pas','Miš',
  'Sova','Zeko','Roda','Mrav','Žaba','Srna','Riba','Orao','Medo','Konj','Koza','Ovca','Buba',
  'Jelen','Patka','Pčela','Kunić','Vrana','Guska','Ronda',
  'Lisica','Leptir','Šišmiš','Lasica','Jazavac','Medvjed','Fazanka','Dabar',
];

// SumskaSlagalica — all letters that can appear as hint letters
const SS_HINT_LETTERS = ['A','B','C','Č','Ć','D','E','F','G','I','J','K','L','M','N','O','P','R','S','Š','T','U','V','Z','Ž'];

// KamoJeNestaoListic items
const KJN_ITEMS = [
  { id: 'zir',      name: 'Žir'      },
  { id: 'gljiva',   name: 'Gljiva'   },
  { id: 'list',     name: 'List'     },
  { id: 'jabuka',   name: 'Jabuka'   },
  { id: 'cvijet',   name: 'Cvijet'   },
  { id: 'bobica',   name: 'Bobica'   },
  { id: 'pero',     name: 'Pero'     },
  { id: 'puz',      name: 'Puž'      },
  { id: 'leptir',   name: 'Leptir'   },
  { id: 'kamen',    name: 'Kamen'    },
  { id: 'jagoda',   name: 'Jagoda'   },
  { id: 'grancica', name: 'Grančica' },
];

// EkoCistac wrong-click items per difficulty
const ECO_WRONG_EASY = ['List', 'Bubamara'];
const ECO_WRONG_HARD = ['List', 'Bubamara', 'Leptir', 'Ptica'];

// ── Slugify helper (ASCII-safe file keys) ─────────────────────────────────────
function slug(str) {
  return str
    .toLowerCase()
    .replace(/č/g, 'ch').replace(/š/g, 'sh').replace(/ž/g, 'zh')
    .replace(/ć/g, 'cj').replace(/đ/g, 'dj')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// ── Build the map ─────────────────────────────────────────────────────────────

const entries = [];

// StartScreen
entries.push(['Dobrodošli u Šumsku Priču! Pritisnite gumb za početak.', 'dobrodosli']);

// GameSelector
entries.push(['Odaberi igru koju želiš igrati!', 'odaberi-igru']);

// EndScreen praise phrases
entries.push(['Bravo! Odlično odrađeno!',   'pohvala-bravo']);
entries.push(['Sjajno! Ti si zvijezda šume!', 'pohvala-sjajno']);
entries.push(['Fantastično! Nastavite tako!', 'pohvala-fantasticno']);
entries.push(['Super posao! Šuma je ponosna!', 'pohvala-super']);

// ZvucnaZagonetka — static
entries.push(['Bravo! Točno!',                   'bravo-tocno']);
entries.push(['Pokušaj ponovo!',                 'pokusaj-ponovo']);
entries.push(['Vrijeme je isteklo! Idemo dalje.','vrijeme-isteklo-dalje']);

// ZvucnaZagonetka — per-letter (uppercase)
for (const letter of ZZ_TARGETS_UPPER) {
  const hint = LETTER_HINT[letter];
  entries.push([`Stisni na prvo slovo u riječi ${hint}!`,         `pronadi-${slug(letter)}`]);
  entries.push([`Pokušaj ponovo! Traži prvo slovo u ${hint}!`,   `trazimo-${slug(letter)}`]);
}
// ZvucnaZagonetka — per-letter (confusable lowercase)
for (const letter of ZZ_TARGETS_LOWER) {
  const hint = LETTER_HINT[letter];
  entries.push([`Stisni na prvo slovo u riječi ${hint}!`,         `pronadi-lower-${slug(letter)}`]);
  entries.push([`Pokušaj ponovo! Traži prvo slovo u ${hint}!`,   `trazimo-lower-${slug(letter)}`]);
}

// KamoJeNestaoListic — static
entries.push(['Zapamti predmete!',           'zapamti-predmete']);
entries.push(['Koji predmet je nestao?',     'koji-predmet']);
entries.push(['To nije taj. Pokušaj ponovo!','to-nije-taj']);

// KamoJeNestaoListic — per-item
for (const item of KJN_ITEMS) {
  entries.push([`Nestao je ${item.name}! Idemo dalje.`, `nestao-${item.id}`]);
  entries.push([`Točno! Nestao je ${item.name}!`,       `tocno-nestao-${item.id}`]);
}

// EkoCistac — static
entries.push(['Bravo! Očistio si šumu!',                                                                           'bravo-ocistio']);
entries.push(['Klikni samo plastične boce! Pazi da ne klikneš listove ili bubamare.', 'klikni-boce-easy']);
entries.push(['Klikni plastične boce i limenke! Ne diraj ostalo!',                     'klikni-boce-hard']);

// EkoCistac — per wrong-item
for (const name of ECO_WRONG_EASY) {
  entries.push([`To je ${name}. Klikni samo plastične boce!`, `to-je-${slug(name)}-easy`]);
}
for (const name of ECO_WRONG_HARD) {
  entries.push([`To je ${name}. Klikni samo boce i limenke!`, `to-je-${slug(name)}-hard`]);
}

// SumskaSlagalica — static
entries.push(['Vrijeme je isteklo! Idemo na sljedeću riječ.', 'vrijeme-sljedeca-rijec']);

// SumskaSlagalica — per-word
for (const display of SS_WORDS) {
  const key = slug(display);
  entries.push([`Složi riječ ${display}!`, `slozi-${key}`]);
  entries.push([`${display}! Bravo!`,      `bravo-rijec-${key}`]);
}

// SumskaSlagalica — hint letters
for (const letter of SS_HINT_LETTERS) {
  entries.push([`Hint: slovo ${letter}!`, `hint-slovo-${slug(letter)}`]);
}

export const AUDIO_MAP = Object.fromEntries(entries);
